// Mocks generated by Mockito 5.4.6 from annotations
// in mood_shift_ai/test/services/speech_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i5;

import 'package:get/get.dart' as _i3;
import 'package:get_storage/get_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:mood_shift_ai/app/services/crashlytics_service.dart' as _i10;
import 'package:mood_shift_ai/app/services/storage_service.dart' as _i4;
import 'package:speech_to_text/speech_to_text.dart' as _i6;
import 'package:speech_to_text_platform_interface/speech_to_text_platform_interface.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetStorage_0 extends _i1.SmartFake implements _i2.GetStorage {
  _FakeGetStorage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageService_2 extends _i1.SmartFake
    implements _i4.StorageService {
  _FakeStorageService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_3 extends _i1.SmartFake implements _i5.Locale {
  _FakeLocale_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_4 extends _i1.SmartFake implements Duration {
  _FakeDuration_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SpeechToText].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechToText extends _i1.Mock implements _i6.SpeechToText {
  MockSpeechToText() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasRecognized => (super.noSuchMethod(
        Invocation.getter(#hasRecognized),
        returnValue: false,
      ) as bool);

  @override
  String get lastRecognizedWords => (super.noSuchMethod(
        Invocation.getter(#lastRecognizedWords),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#lastRecognizedWords),
        ),
      ) as String);

  @override
  String get lastStatus => (super.noSuchMethod(
        Invocation.getter(#lastStatus),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#lastStatus),
        ),
      ) as String);

  @override
  double get lastSoundLevel => (super.noSuchMethod(
        Invocation.getter(#lastSoundLevel),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotListening => (super.noSuchMethod(
        Invocation.getter(#isNotListening),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<bool> get hasPermission => (super.noSuchMethod(
        Invocation.getter(#hasPermission),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  set errorListener(_i6.SpeechErrorListener? value) => super.noSuchMethod(
        Invocation.setter(
          #errorListener,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set statusListener(_i6.SpeechStatusListener? value) => super.noSuchMethod(
        Invocation.setter(
          #statusListener,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set unexpectedPhraseAggregator(_i6.SpeechPhraseAggregator? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #unexpectedPhraseAggregator,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<bool> initialize({
    _i6.SpeechErrorListener? onError,
    _i6.SpeechStatusListener? onStatus,
    dynamic debugLogging = false,
    Duration? finalTimeout = const Duration(milliseconds: 2000),
    List<_i9.SpeechConfigOption>? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #onError: onError,
            #onStatus: onStatus,
            #debugLogging: debugLogging,
            #finalTimeout: finalTimeout,
            #options: options,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<dynamic> listen({
    _i6.SpeechResultListener? onResult,
    Duration? listenFor,
    Duration? pauseFor,
    String? localeId,
    _i6.SpeechSoundLevelChange? onSoundLevelChange,
    dynamic cancelOnError = false,
    dynamic partialResults = true,
    dynamic onDevice = false,
    _i9.ListenMode? listenMode = _i9.ListenMode.confirmation,
    dynamic sampleRate = 0,
    _i9.SpeechListenOptions? listenOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [],
          {
            #onResult: onResult,
            #listenFor: listenFor,
            #pauseFor: pauseFor,
            #localeId: localeId,
            #onSoundLevelChange: onSoundLevelChange,
            #cancelOnError: cancelOnError,
            #partialResults: partialResults,
            #onDevice: onDevice,
            #listenMode: listenMode,
            #sampleRate: sampleRate,
            #listenOptions: listenOptions,
          },
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  void changePauseFor(Duration? pauseFor) => super.noSuchMethod(
        Invocation.method(
          #changePauseFor,
          [pauseFor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<List<_i6.LocaleName>> locales() => (super.noSuchMethod(
        Invocation.method(
          #locales,
          [],
        ),
        returnValue: _i8.Future<List<_i6.LocaleName>>.value(<_i6.LocaleName>[]),
      ) as _i8.Future<List<_i6.LocaleName>>);

  @override
  _i8.Future<_i6.LocaleName?> systemLocale() => (super.noSuchMethod(
        Invocation.method(
          #systemLocale,
          [],
        ),
        returnValue: _i8.Future<_i6.LocaleName?>.value(),
      ) as _i8.Future<_i6.LocaleName?>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i4.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetStorage get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.GetStorage);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_1<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_1<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<_i4.StorageService> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i8.Future<_i4.StorageService>.value(_FakeStorageService_2(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i8.Future<_i4.StorageService>);

  @override
  _i5.Locale getLocale() => (super.noSuchMethod(
        Invocation.method(
          #getLocale,
          [],
        ),
        returnValue: _FakeLocale_3(
          this,
          Invocation.method(
            #getLocale,
            [],
          ),
        ),
      ) as _i5.Locale);

  @override
  void setLocale(
    String? languageCode,
    String? countryCode,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [
            languageCode,
            countryCode,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getLanguageCode() => (super.noSuchMethod(
        Invocation.method(
          #getLanguageCode,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageCode,
            [],
          ),
        ),
      ) as String);

  @override
  String getCountryCode() => (super.noSuchMethod(
        Invocation.method(
          #getCountryCode,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getCountryCode,
            [],
          ),
        ),
      ) as String);

  @override
  String getFullLocale() => (super.noSuchMethod(
        Invocation.method(
          #getFullLocale,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getFullLocale,
            [],
          ),
        ),
      ) as String);

  @override
  String getVoiceGender() => (super.noSuchMethod(
        Invocation.method(
          #getVoiceGender,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getVoiceGender,
            [],
          ),
        ),
      ) as String);

  @override
  void setVoiceGender(String? gender) => super.noSuchMethod(
        Invocation.method(
          #setVoiceGender,
          [gender],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getCurrentStreak() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentStreak,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getLongestStreak() => (super.noSuchMethod(
        Invocation.method(
          #getLongestStreak,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getTotalShifts() => (super.noSuchMethod(
        Invocation.method(
          #getTotalShifts,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool hasShiftedToday() => (super.noSuchMethod(
        Invocation.method(
          #hasShiftedToday,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> incrementStreak() => (super.noSuchMethod(
        Invocation.method(
          #incrementStreak,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int incrementTotalShifts() => (super.noSuchMethod(
        Invocation.method(
          #incrementTotalShifts,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getStreakDay() => (super.noSuchMethod(
        Invocation.method(
          #getStreakDay,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getTodayShifts() => (super.noSuchMethod(
        Invocation.method(
          #getTodayShifts,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void incrementShift() => super.noSuchMethod(
        Invocation.method(
          #incrementShift,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getShiftCounter() => (super.noSuchMethod(
        Invocation.method(
          #getShiftCounter,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void incrementShiftCounter() => super.noSuchMethod(
        Invocation.method(
          #incrementShiftCounter,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetShiftCounter() => super.noSuchMethod(
        Invocation.method(
          #resetShiftCounter,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isAdFree() => (super.noSuchMethod(
        Invocation.method(
          #isAdFree,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setAdFree24Hours() => super.noSuchMethod(
        Invocation.method(
          #setAdFree24Hours,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration getRemainingAdFreeTime() => (super.noSuchMethod(
        Invocation.method(
          #getRemainingAdFreeTime,
          [],
        ),
        returnValue: _FakeDuration_4(
          this,
          Invocation.method(
            #getRemainingAdFreeTime,
            [],
          ),
        ),
      ) as Duration);

  @override
  String getAdFreeEndTime() => (super.noSuchMethod(
        Invocation.method(
          #getAdFreeEndTime,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getAdFreeEndTime,
            [],
          ),
        ),
      ) as String);

  @override
  void clearAdFree() => super.noSuchMethod(
        Invocation.method(
          #clearAdFree,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasCrystalVoice() => (super.noSuchMethod(
        Invocation.method(
          #hasCrystalVoice,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setCrystalVoice1Hour() => super.noSuchMethod(
        Invocation.method(
          #setCrystalVoice1Hour,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration getRemainingCrystalTime() => (super.noSuchMethod(
        Invocation.method(
          #getRemainingCrystalTime,
          [],
        ),
        returnValue: _FakeDuration_4(
          this,
          Invocation.method(
            #getRemainingCrystalTime,
            [],
          ),
        ),
      ) as Duration);

  @override
  String getCrystalVoiceEndTime() => (super.noSuchMethod(
        Invocation.method(
          #getCrystalVoiceEndTime,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getCrystalVoiceEndTime,
            [],
          ),
        ),
      ) as String);

  @override
  void clearCrystalVoice() => super.noSuchMethod(
        Invocation.method(
          #clearCrystalVoice,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastResponse(String? response) => super.noSuchMethod(
        Invocation.method(
          #setLastResponse,
          [response],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getRecentUserInputs() => (super.noSuchMethod(
        Invocation.method(
          #getRecentUserInputs,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> getRecentAIResponses() => (super.noSuchMethod(
        Invocation.method(
          #getRecentAIResponses,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void addUserInputToHistory(String? input) => super.noSuchMethod(
        Invocation.method(
          #addUserInputToHistory,
          [input],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addAIResponseToHistory(String? response) => super.noSuchMethod(
        Invocation.method(
          #addAIResponseToHistory,
          [response],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearConversationHistory() => super.noSuchMethod(
        Invocation.method(
          #clearConversationHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Map<String, dynamic>> getCachedResponses() => (super.noSuchMethod(
        Invocation.method(
          #getCachedResponses,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  void addCachedResponse(
    String? userInput,
    String? response,
    String? language,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addCachedResponse,
          [
            userInput,
            response,
            language,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic>? findCachedResponse(
    String? userInput,
    String? language,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #findCachedResponse,
        [
          userInput,
          language,
        ],
      )) as Map<String, dynamic>?);

  @override
  void clearCachedResponses() => super.noSuchMethod(
        Invocation.method(
          #clearCachedResponses,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isFirstLaunch() => (super.noSuchMethod(
        Invocation.method(
          #isFirstLaunch,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setFirstLaunchComplete() => super.noSuchMethod(
        Invocation.method(
          #setFirstLaunchComplete,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPollyVoiceMap(Map<String, dynamic>? voiceMap) => super.noSuchMethod(
        Invocation.method(
          #setPollyVoiceMap,
          [voiceMap],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearPollyVoiceMap() => super.noSuchMethod(
        Invocation.method(
          #clearPollyVoiceMap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPollyVoiceMapVersion(int? version) => super.noSuchMethod(
        Invocation.method(
          #setPollyVoiceMapVersion,
          [version],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool getCrashReportsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getCrashReportsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setCrashReportsEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setCrashReportsEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CrashlyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsService extends _i1.Mock
    implements _i10.CrashlyticsService {
  MockCrashlyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_1<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_1<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserContext() => super.noSuchMethod(
        Invocation.method(
          #updateUserContext,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reportError(
    dynamic error,
    StackTrace? stackTrace, {
    String? reason,
    Map<String, dynamic>? customKeys,
    bool? fatal = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportError,
          [
            error,
            stackTrace,
          ],
          {
            #reason: reason,
            #customKeys: customKeys,
            #fatal: fatal,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reportLLMError(
    dynamic error,
    StackTrace? stackTrace, {
    required String? operation,
    String? model,
    int? statusCode,
    String? userInput,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportLLMError,
          [
            error,
            stackTrace,
          ],
          {
            #operation: operation,
            #model: model,
            #statusCode: statusCode,
            #userInput: userInput,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reportTTSError(
    dynamic error,
    StackTrace? stackTrace, {
    required String? operation,
    String? engine,
    String? voiceId,
    String? locale,
    int? textLength,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportTTSError,
          [
            error,
            stackTrace,
          ],
          {
            #operation: operation,
            #engine: engine,
            #voiceId: voiceId,
            #locale: locale,
            #textLength: textLength,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reportSpeechError(
    dynamic error,
    StackTrace? stackTrace, {
    required String? operation,
    String? locale,
    bool? isAvailable,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportSpeechError,
          [
            error,
            stackTrace,
          ],
          {
            #operation: operation,
            #locale: locale,
            #isAvailable: isAvailable,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reportNetworkError(
    dynamic error,
    StackTrace? stackTrace, {
    required String? service,
    String? endpoint,
    int? statusCode,
    String? method,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportNetworkError,
          [
            error,
            stackTrace,
          ],
          {
            #service: service,
            #endpoint: endpoint,
            #statusCode: statusCode,
            #method: method,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reportUserFlowError(
    dynamic error,
    StackTrace? stackTrace, {
    required String? flow,
    String? step,
    Map<String, dynamic>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportUserFlowError,
          [
            error,
            stackTrace,
          ],
          {
            #flow: flow,
            #step: step,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reportStorageError(
    dynamic error,
    StackTrace? stackTrace, {
    required String? operation,
    String? key,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportStorageError,
          [
            error,
            stackTrace,
          ],
          {
            #operation: operation,
            #key: key,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reportAdError(
    dynamic error,
    StackTrace? stackTrace, {
    required String? operation,
    required String? adType,
    int? errorCode,
    String? errorMessage,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportAdError,
          [
            error,
            stackTrace,
          ],
          {
            #operation: operation,
            #adType: adType,
            #errorCode: errorCode,
            #errorMessage: errorMessage,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(String? message) => super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> testCrashlytics() => (super.noSuchMethod(
        Invocation.method(
          #testCrashlytics,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void setCrashReportsEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setCrashReportsEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool getCrashReportsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getCrashReportsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
