// This file is auto-generated by FlutterFire CLI
// Replace with your actual Firebase configuration after running:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJkwBJVtr79twIZ1ITPJYbs7mdmDuKzs',
    appId: '1:767376759120:android:0100b73b7a4f6e60d13455',
    messagingSenderId: '767376759120',
    projectId: 'mood-shift-ai',
    storageBucket: 'mood-shift-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLCHpsOtPj8FQSLj1lZyAXcNs_5dwSPM',
    appId: '1:767376759120:ios:c8e95e98beb16370d13455',
    messagingSenderId: '767376759120',
    projectId: 'mood-shift-ai',
    storageBucket: 'mood-shift-ai.firebasestorage.app',
    iosBundleId: 'com.moodshift.ai',
  );
}

